packages:
  - "packages/*"
  - "apps/*"
  - "tooling/*"
catalog:
  "@tailwindcss/postcss": ^4.1.11
  "@tanstack/react-router": ^1.130.12
  "@tanstack/react-router-devtools": ^1.130.13
  "@tanstack/react-start": ^1.130.15
  "@types/node": ^22.5.4
  "@types/react": ^19.0.8
  "@types/react-dom": ^19.0.3
  "@vitejs/plugin-react": ^4.6.0
  autoprefixer: ^10.4.20
  eslint: ^9.33.0
  postcss: ^8.5.6
  prettier: ^3.6.2
  react: ^19.0.0
  react-dom: ^19.0.0
  tailwindcss: ^4.1.11
  typescript: ^5.7.2
  vite: ^6.3.5
  vite-tsconfig-paths: ^5.1.4
  zod: ^3.24.2
